// admin
export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const ADMIN_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
// products
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const COUNT_PRODUCTS = 'COUNT_PRODUCTS';
export const SET_SORTBY = 'SET_SORTBY';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
// categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_LOADING_CATEGORIES = 'SET_LOADING_CATEGORIES';
export const DELETE_CATEGORIE = 'DELETE_CATEGORIE';
export const CREATE_CATEGORIE = 'CREATE_CATEGORIE';
export const GET_CURRENT_CATEGORIE = 'GET_CURRENT_CATEGORIE';
export const UPDATE_CATEGORIE = 'UPDATE_CATEGORIE';
// subcategories
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const SET_LOADING_SUBCATEGORIES = 'SET_LOADING_SUBCATEGORIES';
export const DELETE_SUBCATEGORIE = 'DELETE_SUBCATEGORIE';
export const CREATE_SUBCATEGORIE = 'CREATE_SUBCATEGORIE';
export const GET_CURRENT_SUBCATEGORIE = 'GET_CURRENT_SUBCATEGORIE';
export const UPDATE_SUBCATEGORIE = 'UPDATE_SUBCATEGORIE';
