// admin
export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const ADMIN_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
// products
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const COUNT_PRODUCTS = 'COUNT_PRODUCTS';
export const SET_SORTBY = 'SET_SORTBY';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
// categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_LOADING_CATEGORIES = 'SET_LOADING_CATEGORIES';
export const DELETE_CATEGORIE = 'DELETE_CATEGORIE';
export const CREATE_CATEGORIE = 'CREATE_CATEGORIE';
export const GET_CURRENT_CATEGORIE = 'GET_CURRENT_CATEGORIE';
export const UPDATE_CATEGORIE = 'UPDATE_CATEGORIE';
export const SET_CAT_IMAGE = 'SET_CAT_IMAGE';
// subcategories
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const SET_LOADING_SUBCATEGORIES = 'SET_LOADING_SUBCATEGORIES';
export const DELETE_SUBCATEGORIE = 'DELETE_SUBCATEGORIE';
export const CREATE_SUBCATEGORIE = 'CREATE_SUBCATEGORIE';
export const GET_CURRENT_SUBCATEGORIE = 'GET_CURRENT_SUBCATEGORIE';
export const UPDATE_SUBCATEGORIE = 'UPDATE_SUBCATEGORIE';
export const SET_SUB_IMAGE = 'SET_SUB_IMAGE';
// brands
export const GET_BRANDS = 'GET_BRANDS';
export const SET_LOADING_BRANDS = 'SET_LOADING_BRANDS';
export const DELETE_BRAND = 'DELETE_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';
export const GET_CURRENT_BRAND = 'GET_CURRENT_BRAND';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const SET_BRN_IMAGE = 'SET_BRN_IMAGE';
// stores
export const GET_STORES = 'GET_STORES';
export const SET_LOADING_STORES = 'SET_LOADING_STORES';
export const DELETE_STORE = 'DELETE_STORE';
export const CREATE_STORE = 'CREATE_STORE';
export const GET_CURRENT_STORE = 'GET_CURRENT_STORE';
export const UPDATE_STORE = 'UPDATE_STORE';
